version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: springevent
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1234
      MYSQL_RANDOM_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springevent?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379